<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$isHomepage = $site->homepage()->siteUrl() == preg_replace('/[\?#].*/','',$_SERVER['REQUEST_URI']);
$hasHeadingFont = $this->themeSetting('heading_font') && $this->themeSetting('heading_font_url') && $this->themeSetting('heading_font_type');
$hasBodyFont = $this->themeSetting('body_font') && $this->themeSetting('body_font_url') && $this->themeSetting('body_font_type');
$logoBg = $this->themeSetting('logo_bg') ? 'background-color: transparent; background-image:url('.$this->themeSettingAssetUrl('logo_bg').');' : '';
$footerBranding = $this->themeSetting('footer_branding_text') ? $escape($this->themeSetting('footer_branding_text')) : '';
if($this->themeSetting('footer_branding_text') && $this->themeSetting('footer_branding_logo')):
    $footerBranding = '<img class="site-footer-logo" src="'.$this->themeSettingAssetUrl('footer_branding_logo').'" alt="'.$escape($this->themeSetting('footer_branding_text')).'">';
endif;
if ($isHomepage == true): 
    $this->htmlElement('body')->appendAttribute('class', 'homepage');
endif;
$themeSettingCSS = function ($setting,$property){
    if($this->themeSetting($setting)): 
        return $property.':'.$this->themeSetting($setting).';';
    else:
        return '';
    endif;
};
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic');
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headScript()->prependFile($this->assetUrl('js/centerrow.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$headingSheet = '//fonts.googleapis.com/css?family=Lato';
$bodySheet = '//fonts.googleapis.com/css?family=Lato';
if($hasHeadingFont):
    preg_replace('^/.*\/\/','//',$this->themeSetting('heading_font_url'));
endif;
if($hasBodyFont):
    preg_replace('^/.*\/\/','//',$this->themeSetting('body_font_url'));
endif;
if($headingSheet !== $bodySheet): 
    $this->headLink()->prependStylesheet($headingSheet);
endif;
$this->headLink()->prependStylesheet($bodySheet);
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <style>
            html {
                font-size: 20px;
                line-height: 160%;
                <?php if($this->themeSetting('text_color')): ?>
                --text-color:<?php echo $this->themeSetting('text_color')?>;
                <?php endif; ?><?php if($this->themeSetting('bg_color')): ?>
                --bg-color:<?php echo $this->themeSetting('bg_color')?>;
                <?php endif; ?><?php if($this->themeSetting('primary_accent')): ?>
                --primary-accent-color:<?php echo $this->themeSetting('primary_accent')?>;
                <?php endif; ?><?php if($this->themeSetting('secondary_accent')): ?>
                --secondary-accent-color:<?php echo $this->themeSetting('secondary_accent')?>;
                <?php endif; ?><?php if($hasBodyFont): ?>
                font-family:<?php echo $this->themeSetting('body_font').','.$this->themeSetting('body_font_type'); ?>
                <?php endif; ?>
            }
            body {
                color: var(--text-color);
            }
            .large.file {
                margin: 0 auto 24px;
            }
            body.homepage .large.file {
                float: none;
            }
            body.homepage .large.file,
            body.homepage .large.file *,
            body.homepage .large.file .media-render>a:first-child {
                width: 100%;
                display: block;
            }
            body .large.file .resource  {
                margin: 0;
            }
            header {
                background-color: var(--secondary-accent-color);
                background-size:cover;
                <?php echo $logoBg; ?>
                <?php echo $themeSettingCSS('logo_bg_repeat','background-repeat');?>
                <?php echo $themeSettingCSS('logo_bg_position_x','background-position-x');?>
                <?php echo $themeSettingCSS('logo_bg_position_y','background-position-y');?>
            }
            <?php if($hasHeadingFont): ?>
            h1,h2,h3 {
                font-family:<?php echo $this->themeSetting('heading_font').','.$this->themeSetting('heading_font_type'); ?>
            }
            <?php endif; ?>
            h1 {
                margin-bottom: 0;
            }
            .site-title {
                display: flex;
                padding: 2px 10px;
                align-items: stetch;
                <?php echo $themeSettingCSS('logo_position_x','justify-content');?>
            }
            .site-title img {
                min-height: 150px;
                max-height: 200px;
                <?php echo $themeSettingCSS('logo_margin','margin');?>
            }
            header nav .navigation {
                margin: 0;
                background-color: var(--primary-accent-color);
                border-color: var(--text-color);
            }
            header nav a, h1 a {
                font-size: 18px;
                color: var(--bg-color);
                text-transform: unset;
            }
            .page #content .sub-menu {
                padding: 0 24px 24px 0;
                width: 200px;
            }
            .page #content .sub-menu ~ *:not(.site-page-pagination) {
                width: calc(100% - 200px);
            }
            .page #content .sub-menu a {
                font-size: 18px;
                color: var(--primary-accent-color);
            }
            .caption {
                font-size: 14px;
                line-height: 130%;
            }
            #content .sub-menu,
            #content .blocks > h2:first-child {
                margin-top: 12px;
            }
            #content .blocks>h2:first-of-type {
                text-align: left;
            }
            .site-page-pagination > a:last-child {
                float: right;
            }
            footer {
                padding: 20px;
                margin-top: 12px;
                color: var(--bg-color);
                background-color: var(--secondary-accent-color);
                display: flex;
                align-items: stretch;
                justify-content: space-between;
            }
            footer ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                display: flex;
                align-items: flex-start;
                justify-content: space-between;
            }
            footer li {
                padding: 0 0.5em;
            }
            footer li:first-child {
                padding-left: 0;
            }
            footer li:last-child {
                padding-right: 0;
            }
            footer li:not(:last-child):after {
                content: ' | ';
                padding: 0 0.5em;
            }
            footer a {
                color: var(--bg-color);
            }
            footer a:visited {
                color: var(--bg-color);
            }
            .site-footer-logo {
                width: 160px;
                height: auto;
            }
            .site-footer-text {
                font-size: 80%;
            }
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <div id="wrap">
            <header>
                <h1>
                    <a href="<?php echo $site->url(); ?>" class="site-title">
                    <?php if ($this->themeSetting('logo')): ?>
                        <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                    <?php else: ?>
                        <?php echo $escape($siteTitle); ?>
                    <?php endif; ?>
                    </a>
                </h1>
                <div id="search-container">
                    <?php echo $this->partial('common/search-form'); ?>
                    <button type="button" class="search-toggle" title="Toggle search"></button>
                </div>
                <nav>
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => $this->themeSetting('nav_depth') - 1
                ]);
                ?>
                </nav>
            </header>

            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>

            <footer>
                <?php if ($this->themeSetting('footer_branding_url') && $this->themeSetting('footer_branding_text')): ?>
                    <a href="<?php echo $this->themeSetting('footer_branding_url')?>" 
                        title="<?php $escape($this->themeSetting('footer_branding_text')) ?>">
                        <?php echo $footerBranding ?>
                    </a>
                <?php else: ?>
                    <?php echo $footerBranding ?>
                <?php endif; ?>
                <div class="site-footer-text">
                    <?php if ($footerContent = $this->themeSetting('footer')): ?>
                        <?php echo $footerContent; ?>
                    <?php else: ?>
                        <?php echo $this->translate('Powered by Omeka S');?>
                    <?php endif; ?>
                </div>
            </footer>
        </div>
        <div hidden><?php echo print_r(array_keys(get_defined_vars($this->helper))); ?></div>
        <div hidden><?php echo print_r(array_keys(get_defined_functions('user'))) ?></div>
        <div hidden><?php echo print_r(array_keys($this->helper)) ?></div>
    </body>
</html>